### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by aferraz** [Freemanium/govee_btled#3]
Hi,
 sorry I don't understand how to use it.
I create a test.py:
**from govee_btled import BluetoothLED
led = BluetoothLED('A4:C1:38:A1:FB:5D')
led.set_state(True)
led.set_color('blue')**

But I got this error:
Traceback (most recent call last):
  _File "test.py", line 1, in <module>
    from govee_btled import BluetoothLED
  File "/home/pi/govee_btled-master/govee_btled/__init__.py", line 3, in <module>
    from .bluetooth_led import BluetoothLED
  File "/home/pi/govee_btled-master/govee_btled/bluetooth_led.py", line 94
    raise ValueError(f'Brightness out of range: {value}')_

Can you help me ?

Thanks
 Alessandro

**Comment by chvolkmann** [comment]
Is that the entire error output?

**Comment by chvolkmann** [comment]
Closing due to inactivity. Feel free to reopen.
